Repository YannRaulet/retroCycling, pull requests merged in 2021-03, with the labels that each got.

#2 Creation of CRUD Article entity and add node SASS loader
  assets/app.js
  assets/styles/app.css
  assets/styles/app.scss
  assets/styles/crud.scss
  config/packages/twig.yaml
  package-lock.json
  package.json
  src/Controller/AdminBlogController.php
  src/Controller/AdminFrontController.php
  src/Entity/Article.php
  src/Form/ArticleType.php
  templates/admin/admin_layout.html.twig
  templates/admin/article_delete_form.html.twig
  templates/admin/article_edit.html.twig
  templates/admin/article_form.html.twig
  templates/admin/article_new.html.twig
  templates/admin/article_show.html.twig
  templates/admin/articles.html.twig
  templates/admin/blog.html.twig
  templates/admin/collection.html.twig
  templates/admin/home.html.twig
  templates/admin/shirt_cycling.html.twig
  webpack.config.js
  yarn.lock
Labels: review requested

#4 navBar
  assets/app.js
  assets/styles/app.scss
  assets/styles/navBar.scss
  package.json
  public/assets/images/logo-retro.png
  public/assets/images/logo-retro.svg
  public/assets/images/play-button.png
  templates/base.html.twig
  templates/front/front_layout.html.twig
  yarn.lock
Labels: review requested

#3 Create CRUD of entity category and add function for convert ToString
  assets/styles/crud.scss
  src/Controller/AdminCategoryController.php
  src/Entity/Article.php
  src/Entity/Category.php
  src/Form/ArticleType.php
  src/Form/CategoryType.php
  templates/admin/article_delete_form.html.twig
  templates/admin/article_form.html.twig
  templates/admin/article_show.html.twig
  templates/admin/articles.html.twig
  templates/admin/blog.html.twig
  templates/admin/categories.html.twig
  templates/admin/category_delete_form.html.twig
  templates/admin/category_edit.html.twig
  templates/admin/category_form.html.twig
  templates/admin/category_new.html.twig
Labels: review requested

#5 navBar-admin
  templates/admin/admin_layout.html.twig
Labels: reviewed

#6 Add CRUD of ArticleContent entity
  assets/styles/app.scss
  src/Controller/AdminBlogController.php
  src/Controller/AdminCategoryController.php
  src/Entity/Article.php
  src/Entity/ArticleContent.php
  src/Form/ArticleContentType.php
  templates/admin/article_form.html.twig
  templates/admin/blog.html.twig
  templates/admin/category_new.html.twig
  templates/admin/content_delete_form.html.twig
  templates/admin/content_edit.html.twig
  templates/admin/content_form.html.twig
  templates/admin/content_new.html.twig
  templates/admin/content_show.html.twig
  templates/admin/contents.html.twig
Labels: review requested

#7 Add CRUD of CyclingShirt entity
  src/Controller/AdminCyclingShirtController.php
  src/Entity/CyclingShirt.php
  src/Form/CyclingShirtType.php
  templates/admin/article_show.html.twig
  templates/admin/category_new.html.twig
  templates/admin/collection.html.twig
  templates/admin/cycling_shirt_delete_form.html.twig
  templates/admin/cycling_shirt_edit.html.twig
  templates/admin/cycling_shirt_form.html.twig
  templates/admin/cycling_shirt_new.html.twig
  templates/admin/cycling_shirt_show.html.twig
  templates/admin/cycling_shirts.html.twig
  templates/admin/shirt_cycling.html.twig
Labels: Changes done, review requested

#10 Us1 home
  assets/app.js
  assets/images/home-picture.jpg
  assets/images/nordwood.png
  assets/styles/app.scss
  assets/styles/home.scss
  public/assets/images/L'economique.jpg
  public/assets/images/Milremo.jpg
  public/assets/images/Olida-68.jpg
  public/assets/images/logo-retro.svg
  public/assets/images/play-button.png
  templates/front/home.html.twig
Labels: reviewed

#8 Add bundle uploads image for entities
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20210304140117.php
  migrations/Version20210304145856.php
  src/Controller/AdminCyclingShirtController.php
  src/Entity/Article.php
  src/Entity/CyclingShirt.php
  src/Form/ArticleType.php
  src/Form/CyclingShirtType.php
  symfony.lock
  templates/admin/article_show.html.twig
  templates/admin/articles.html.twig
  templates/admin/collection.html.twig
  templates/admin/cycling_shirt_show.html.twig
  templates/admin/cycling_shirts.html.twig
Labels: review requested

#11 us2-shirts-description
  assets/app.js
  assets/styles/app.scss
  assets/styles/collection.scss
  assets/styles/home.scss
  migrations/Version20210308130547.php
  public/assets/images/uploads/gan-1996-604637bc7b04d131230074.jpg
  public/assets/images/uploads/l-economique-604601722405b972464988.jpg
  public/assets/images/uploads/l-economique-60464605d4104409452937.jpg
  public/assets/images/uploads/leader-montagne-1984-6046380b34a08408776220.jpg
  public/assets/images/uploads/maillot-jaune-1993-604637d5952bb104226725.jpg
  public/assets/images/uploads/milremo-6045fa039e661351611117.jpg
  public/assets/images/uploads/olida-68-6045fa19824e2431722106.jpg
  public/assets/images/uploads/olida-68-60464d685feec062437968.jpg
  public/assets/images/uploads/peugeot-1985-604637ef352f8331446111.jpg
  src/Controller/FrontCollectionController.php
  src/Controller/FrontController.php
  src/Entity/CyclingShirt.php
  src/Form/CyclingShirtType.php
  templates/admin/cycling_shirt_form.html.twig
  templates/admin/cycling_shirt_show.html.twig
  templates/admin/cycling_shirts.html.twig
  templates/front/collection.html.twig
  templates/front/collection5060.html.twig
  templates/front/collection70.html.twig
  templates/front/collection80.html.twig
  templates/front/collection90.html.twig
  templates/front/front_layout.html.twig
  templates/front/home.html.twig
  templates/front/shirtCycling5060.html.twig
  templates/front/shirtCycling70.html.twig
  templates/front/shirtCycling80.html.twig
  templates/front/shirtCycling90.html.twig
  templates/front/shirt_cycling.html.twig
Labels: reviewed

#12 Display all articles in the blog with his content
  assets/app.js
  assets/styles/article.scss
  assets/styles/blog.scss
  assets/styles/crud.scss
  composer.lock
  public/assets/images/uploads/expo2013-1-60473091e1781617439170.jpg
  public/assets/images/uploads/expo2013-1-60474df1848e5541428764.jpg
  public/assets/images/uploads/header-merckx-6045ec8c5d6e6682373813.jpg
  public/assets/images/uploads/photo-devlaeminck-6045ec5889a34899835693.jpg
  src/Controller/FrontController.php
  templates/front/article.html.twig
  templates/front/blog.html.twig
Labels: review requested

#16 add second shirt picture in admin part and modify cycling-shirt front…
  assets/controllers/hello_controller.js
  assets/styles/cyclingShirt.scss
  assets/switchCyclingShirt.js
  config/packages/vich_uploader.yaml
  migrations/Version20210310142416.php
  package.json
  public/assets/images/uploads/gan-1996-6049da65645b5608691728.jpg
  public/assets/images/uploads/home-picture-6048a6ae48635136403599.jpg
  public/assets/images/uploads/olida-68-6048d6b5699cf118109900.jpg
  src/Entity/CyclingShirt.php
  src/Form/CyclingShirtType.php
  templates/admin/cycling_shirt_show.html.twig
  templates/admin/cycling_shirts.html.twig
  templates/base.html.twig
  templates/front/collection5060.html.twig
  templates/front/collection70.html.twig
  templates/front/collection80.html.twig
  templates/front/collection90.html.twig
  templates/front/shirtCycling5060.html.twig
  templates/front/shirtCycling70.html.twig
  templates/front/shirtCycling80.html.twig
  templates/front/shirtCycling90.html.twig
  webpack.config.js
  yarn.lock
Labels: review requested

#17 Add script button for sharing an article
  assets/app.js
  assets/social.js
  assets/styles/app.scss
  assets/styles/article.scss
  public/assets/images/logo-facebook.png
  public/assets/images/logo-google.png
  public/assets/images/logo-linkedin.png
  public/assets/images/logo-twitter.png
  public/assets/images/separateur.png
  templates/admin/admin_layout.html.twig
  templates/admin/article_edit.html.twig
  templates/admin/article_new.html.twig
  templates/admin/article_show.html.twig
  templates/admin/articles.html.twig
  templates/admin/blog.html.twig
  templates/admin/categories.html.twig
  templates/admin/category_edit.html.twig
  templates/admin/category_new.html.twig
  templates/admin/collection.html.twig
  templates/admin/content_edit.html.twig
  templates/admin/content_new.html.twig
  templates/admin/content_show.html.twig
  templates/admin/contents.html.twig
  templates/admin/cycling_shirt_edit.html.twig
  templates/admin/cycling_shirt_new.html.twig
  templates/admin/cycling_shirt_show.html.twig
  templates/admin/cycling_shirts.html.twig
  templates/admin/home.html.twig
  templates/base.html.twig
  templates/front/article.html.twig
  templates/front/blog.html.twig
  templates/front/collection5060.html.twig
  templates/front/collection70.html.twig
  templates/front/collection80.html.twig
  templates/front/collection90.html.twig
  templates/front/contact.html.twig
  templates/front/front_layout.html.twig
  templates/front/home.html.twig
  templates/front/shirtCycling5060.html.twig
  templates/front/shirtCycling70.html.twig
  templates/front/shirtCycling80.html.twig
  templates/front/shirtCycling90.html.twig
  webpack.config.js
Labels: review requested

#18 shirt-picture-admin
  assets/styles/cyclingShirt.scss
  assets/switchCyclingShirt.js
  templates/front/shirtCycling5060.html.twig
  templates/front/shirtCycling70.html.twig
  templates/front/shirtCycling80.html.twig
  templates/front/shirtCycling90.html.twig
Labels: review requested

#19 modify shirt description pages
  assets/styles/collection.scss
  assets/styles/cyclingShirt.scss
  public/assets/images/uploads/peugeot-1985-604f19e7bc530793861617.jpg
  public/assets/images/uploads/peugeot-1985-604f1b367bc9d120311859.jpg
  templates/front/shirtCycling5060.html.twig
  templates/front/shirtCycling70.html.twig
  templates/front/shirtCycling80.html.twig
  templates/front/shirtCycling90.html.twig
Labels: review requested

#20 correction bug
  assets/styles/blog.scss
  assets/styles/crud.scss
  public/assets/images/separateur.png
  public/assets/images/uploads/banque-de-bretagne-1982-604f1e5e78046710555201.jpg
  public/assets/images/uploads/bic-1974-604f1d34a9728453942105.jpg
  public/assets/images/uploads/bic-long-1973-604f1d34b23f1897680236.jpg
  public/assets/images/uploads/equipe-bretagne-1985-604f1e5e7e80d123942519.jpg
  public/assets/images/uploads/equipe-z-1990-604f1f2625b7e025123308.jpg
  public/assets/images/uploads/expo2013-1-60474df1848e5541428764.jpg
  public/assets/images/uploads/festina-watches-1994-604f1f262bfac305493213.jpg
  public/assets/images/uploads/festina-watches-1994-604f62029c5fe282130244.jpg
  public/assets/images/uploads/gitane-cafe-meo-1-604f1cd94f23a033044802.jpg
  public/assets/images/uploads/helyett-hutchinson-604f1cd95f577033801648.jpg
  src/Form/ArticleContentType.php
  src/Form/ArticleType.php
  src/Form/CyclingShirtType.php
  templates/admin/article_edit.html.twig
  templates/admin/article_form.html.twig
  templates/admin/article_new.html.twig
  templates/admin/article_show.html.twig
  templates/admin/articles.html.twig
  templates/admin/blog.html.twig
  templates/admin/categories.html.twig
  templates/admin/category_edit.html.twig
  templates/admin/category_form.html.twig
  templates/admin/category_new.html.twig
  templates/admin/content_edit.html.twig
  templates/admin/content_form.html.twig
  templates/admin/content_new.html.twig
  templates/admin/content_show.html.twig
  templates/admin/contents.html.twig
  templates/admin/cycling_shirt_edit.html.twig
  templates/admin/cycling_shirt_new.html.twig
  templates/admin/cycling_shirt_show.html.twig
  templates/admin/cycling_shirts.html.twig
Labels: review requested

#25 Us1 home
  assets/styles/article.scss
  assets/styles/home.scss
  public/assets/images/uploads/l-economique-6050c9f49f45b724808736.jpg
  public/assets/images/uploads/milremo-6050c92d85b5c680109037.jpg
  public/assets/images/uploads/milremo-6050c9d814ae3667091812.jpg
  src/Controller/FrontController.php
  templates/front/home.html.twig
Labels: reviewed

#26 authentication user and admin
  assets/app.js
  assets/styles/login.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  migrations/Version20210318132537.php
  migrations/Version20210318143314.php
  migrations/Version20210318170052.php
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/front/front_layout.html.twig
  templates/security/login.html.twig
  templates/security/registrer.html.twig
Labels: review requested

#28 style login
  assets/images/login-picture.jpg
  assets/styles/app.scss
  assets/styles/login.scss
  templates/security/login.html.twig
Labels: review requested

#29 registration form display
  assets/app.js
  assets/styles/login.scss
  assets/styles/registrer.scss
  templates/security/registrer.html.twig
Labels: review requested

#31 Background picture crud
  config/packages/vich_uploader.yaml
  migrations/Version20210323100907.php
  migrations/Version20210323134628.php
  public/assets/images/uploads/nordwood-6059f5d50d209004044589.png
  public/assets/images/uploads/olida-68-6059a2580fc4b499883939.jpg
  public/assets/images/uploads/olida-68-6059e9ef802a9337897142.jpg
  public/assets/images/uploads/peugeot-1985-6059e9ef7ee17921350146.jpg
  src/Controller/AdminBackgroundPictureController.php
  src/Entity/BackgroundPicture.php
  src/Form/BackgroundPictureType.php
  src/Repository/BackgroundPictureRepository.php
  templates/admin/background_picture_delete_form.html.twig
  templates/admin/background_picture_edit.html.twig
  templates/admin/background_picture_form.html.twig
  templates/admin/background_picture_new.html.twig
  templates/admin/background_picture_show.html.twig
  templates/admin/background_pictures.html.twig
  templates/admin/cycling_shirt_edit.html.twig
  templates/admin/home.html.twig
Labels: review requested

#32 Mailer contact form
  .env
  assets/app.js
  assets/styles/contact.scss
  assets/styles/login.scss
  assets/styles/registrer.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/swiftmailer.yaml
  config/packages/dev/web_profiler.yaml
  config/packages/swiftmailer.yaml
  config/packages/test/swiftmailer.yaml
  src/Controller/FrontController.php
  src/Form/ContactType.php
  symfony.lock
  templates/emails/contact.html.twig
  templates/front/contact.html.twig
  templates/front/contact_us.html.twig
  templates/front/front_layout.html.twig
  templates/security/registrer.html.twig
Labels: review requested

#33 fix bug Background image vich
  migrations/Version20210324090546.php
  public/assets/images/uploads/peugeot-1985-605b013b9f2c7895280806.jpg
Labels: review requested

#34 Us 24 activation account
  assets/social.js
  assets/styles/article.scss
  assets/styles/login.scss
  composer.json
  composer.lock
  migrations/Version20210324095735.php
  migrations/Version20210324140417.php
  public/assets/images/uploads/header-merckx-6045ec8c5d6e6682373813-605db7e460343932759639.jpg
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Form/ResetPassType.php
  templates/base.html.twig
  templates/emails/activation.html.twig
  templates/emails/forgotten_pass.html.twig
  templates/front/article.html.twig
  templates/security/forgotten_password.html.twig
  templates/security/login.html.twig
  templates/security/reset_password.html.twig
Labels: review requested

#35 update loginAuthenticator
  .env
  composer.json
  composer.lock
  config/packages/lock.yaml
  config/packages/security.yaml
  config/packages/translation.yaml
  src/Controller/SecurityController.php
  src/EventSubscriber/RequestSubscriber.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  translations/security.en.xlf
  translations/security.fr.xlf
Labels: review requested
